CONF_FILE_PATH: controller/config.yml
DB_HOST: localhost
DB_PORT: '27017'
DB_URI: mongodb
DEBUG_DB_NAME: Bugfixes
DEBUG_DB_PATTERNS_COLLECTION: BugPatterns
DEBUG_DB_REPO_COLLECTION: RepoData
MAXIMUM_TEST_TIMEOUT: '0.1'
MINING_DB_NAME: Bugfixes
MINING_DB_PATTERNS_COLLECTION: pat
MINING_DB_REPO_COLLECTION: repo
SUSPICIOUSNESS_THRESHOLD: '0'
